# permissions for end users to view replicatedconfigmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicatedconfigmap-viewer-role
rules:
- apiGroups:
  - replications.example.io
  resources:
  - replicatedconfigmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replications.example.io
  resources:
  - replicatedconfigmaps/status
  verbs:
  - get
